#ifndef REPLACEMENTSCHEMA_GLOBAL_H
#define REPLACEMENTSCHEMA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REPLACEMENTSCHEMA_LIBRARY)
#  define REPLACEMENTSCHEMA_EXPORT Q_DECL_EXPORT
#else
#  define REPLACEMENTSCHEMA_EXPORT Q_DECL_IMPORT
#endif

#endif // REPLACEMENTSCHEMA_GLOBAL_H
